# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - sui move test
    sources:
      - sources/**/*.move
      - Move.toml
  demo:
    cmds:
      - yarn ts-node demo/demo.ts
    sources:
      - demo/demo.ts
      - .env
