# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - sui move build --skip-fetch-latest-git-deps
    sources:
      - sources/**/*.move
      - Move.toml
  test:
    cmds:
      - sui move test --skip-fetch-latest-git-deps
    sources:
      - sources/**/*.move
      - Move.toml
  demo:
    deps:
      - build
    cmds:
      - yarn ts-node demo/demo.ts
    sources:
      - demo/demo.ts
      - .env
